/**
   v142 — icon system audit.

   The site used to render its UI out of emoji: font glyphs whose appearance
   depends on the visitor's device (Apple vs Segoe vs Noto) and which show as a
   tofu box where the font lacks the codepoint. This locks in the replacement:
   real SVG icons, generated by tools/icon-forge/make_icons.py.

   What it enforces:
     1. every icon referenced by the markup exists as BOTH a colour and mono SVG
     2. every mono icon has a CSS mask rule, and no rule points at a missing file
     3. the wired UI carries no emoji any more (regression guard)
     4. i18n strings carry no emoji icons - they are presentation, not content,
        and applyI18n() writes textContent, which would erase a child icon
     5. the generated SVGs are well-formed and the mono set is currentColor
*/
'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const exists = (p) => fs.existsSync(path.join(ROOT, p));

const HTML = read('public/index.html');
const CSS = read('public/css/style.css');
const I18N = read('public/js/i18n.js');
const GAME = read('public/js/game.js');

const COLOUR_DIR = 'public/img/ico';
const MONO_DIR = 'public/img/ico-mono';
const colourIcons = fs.readdirSync(path.join(ROOT, COLOUR_DIR)).filter((f) => f.endsWith('.svg'));
const monoIcons = fs.readdirSync(path.join(ROOT, MONO_DIR)).filter((f) => f.endsWith('.svg'));

const EMOJI = /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{2705}\u{274C}\u{26A0}]/u;

test('v142: the colour and mono icon sets are the same size and the same names', () => {
  assert.ok(colourIcons.length >= 24, 'at least the 24 phase-1/2 icons exist, got ' + colourIcons.length);
  assert.deepEqual(colourIcons.slice().sort(), monoIcons.slice().sort(),
    'every icon must exist in both styles - a mono-only or colour-only icon is a broken reference');
});

test('v142: every icon referenced by index.html actually exists on disk', () => {
  const refs = [...HTML.matchAll(/data-i="([a-z0-9-]+)"/g)].map((m) => m[1]);
  assert.ok(refs.length > 0, 'the page must reference icons');
  for (const name of refs) {
    assert.ok(exists(`${MONO_DIR}/${name}.svg`), `mono icon missing for data-i="${name}"`);
  }
  const imgs = [...HTML.matchAll(/img\/ico\/([a-z0-9-]+)\.svg/g)].map((m) => m[1]);
  for (const name of imgs) {
    assert.ok(exists(`${COLOUR_DIR}/${name}.svg`), `colour icon missing: ${name}.svg`);
  }
});

test('v142: every mono icon referenced in the page has a CSS mask rule', () => {
  const refs = [...new Set([...HTML.matchAll(/data-i="([a-z0-9-]+)"/g)].map((m) => m[1]))];
  for (const name of refs) {
    assert.match(CSS, new RegExp(`\\.ico\\[data-i="${name}"\\]`),
      `no .ico[data-i="${name}"] rule - the icon would render as a blank box`);
  }
});

test('v142: no CSS mask rule points at an icon file that does not exist', () => {
  const rules = [...CSS.matchAll(/\.ico\[data-i="([a-z0-9-]+)"\]/g)].map((m) => m[1]);
  assert.ok(rules.length >= 24, 'the icon CSS should cover the full set, got ' + rules.length);
  for (const name of rules) {
    assert.ok(exists(`${MONO_DIR}/${name}.svg`), `CSS references a missing icon: ${name}.svg`);
  }
});

test('v142: the wired UI no longer renders emoji icons', () => {
  // the elements we converted must not still carry a glyph
  const wired = [
    'id="tc-left"', 'id="tc-right"', 'id="tc-nitro"', 'id="tc-brake"', 'id="tc-gas"',
    'id="cam-btn"', 'id="net-banner"', 'id="hud-weather"', 'id="restart-btn"', 'id="sens-title"'
  ];
  for (const id of wired) {
    const at = HTML.indexOf(id);
    assert.ok(at !== -1, `${id} must still exist`);
    const line = HTML.slice(at, HTML.indexOf('\n', at));
    assert.ok(!EMOJI.test(line), `${id} still renders an emoji: ${line.trim().slice(0, 90)}`);
  }
  // and the weather picker
  for (const w of ['dry', 'wet', 'night', 'blizzard']) {
    const at = HTML.indexOf(`data-weather="${w}"`);
    assert.ok(at !== -1, `weather button ${w} exists`);
    const block = HTML.slice(at, HTML.indexOf('</button>', at));
    assert.ok(!EMOJI.test(block), `weather button "${w}" still renders an emoji`);
    assert.match(block, /class="ico weather-ico" data-i="weather-/, `weather button "${w}" needs an icon`);
  }
});

test('v142: emoji were stripped from the i18n strings that now carry icons', () => {
  // icons live in markup; content lives in the dictionary. applyI18n() uses
  // textContent, so an icon inside a translated string would be erased anyway.
  const keys = ['camBtn', 'netBanner', 'practiceLabel', 'restart',
    'sensLabel', 'wDry', 'wWet', 'wNight', 'wBlizzard'];
  for (const key of keys) {
    const hits = [...I18N.matchAll(new RegExp(`^\\s*${key}: '([^']*)'`, 'gm'))];
    assert.ok(hits.length >= 1, `${key} must still exist in the dictionary`);
    for (const h of hits) {
      assert.ok(!EMOJI.test(h[1]), `${key} still contains an emoji icon: ${h[1]}`);
    }
  }
});

test('v142: applyI18n cannot erase an icon (icons are never i18n targets)', () => {
  // a data-i18n element gets textContent = string, which deletes child elements.
  // so no element may carry BOTH an icon and an i18n attribute.
  const withI18n = [...HTML.matchAll(/<([a-z0-9]+)([^>]*data-i18n[^>]*)>/g)];
  for (const [, tag, attrs] of withI18n) {
    assert.ok(!/class="ico/.test(attrs) && !/data-i="/.test(attrs),
      `<${tag}> carries an icon AND data-i18n - the icon would be wiped on language switch`);
  }
});

test('v142: the generated SVGs are well-formed, and mono icons are tintable', () => {
  for (const f of colourIcons) {
    const svg = fs.readFileSync(path.join(ROOT, COLOUR_DIR, f), 'utf8');
    assert.match(svg, /^<!--.*-->\s*<svg[^>]*viewBox="0 0 128 128"/s, `${f}: must open with the generated header + viewBox`);
    assert.ok(svg.trimEnd().endsWith('</svg>'), `${f}: must close properly`);
    assert.ok(!/<script|onload=/i.test(svg), `${f}: no script content in an icon`);
  }
  for (const f of monoIcons) {
    const svg = fs.readFileSync(path.join(ROOT, MONO_DIR, f), 'utf8');
    // a mask is painted entirely by CSS, so every shape must be currentColor
    assert.match(svg, /fill="currentColor"/, `${f}: mono icons must use currentColor`);
    assert.ok(!/url\(#/.test(svg), `${f}: mono icons must not reference gradients (a mask needs flat alpha)`);
  }
});

test('v142: the icon forge is the single source of truth and still runs', () => {
  const forge = path.join(ROOT, 'tools', 'icon-forge', 'make_icons.py');
  assert.ok(fs.existsSync(forge), 'tools/icon-forge/make_icons.py must exist - it regenerates every icon');
  const src = fs.readFileSync(forge, 'utf8');
  assert.match(src, /def write_assets/, 'the forge must know how to emit the asset files');
  assert.match(src, /def mono_svg/, 'the forge must emit the mono variants too');
});

test('v142: the service worker precaches the icons the first paint needs', () => {
  const SW = read('public/sw.js');
  for (const f of ['weather-sun', 'weather-rain', 'weather-snow', 'weather-night',
    'camera', 'gamepad', 'refresh', 'warning', 'steering-wheel']) {
    assert.ok(SW.includes(`ico-mono/${f}.svg`), `sw.js should precache the mono icon ${f} (it is drawn on first paint)`);
  }
  for (const f of ['arrow-up', 'arrow-down', 'arrow-left', 'arrow-right', 'nitro']) {
    assert.ok(SW.includes(`ico/${f}.svg`), `sw.js should precache the colour icon ${f}`);
  }
  const cache = SW.match(/const CACHE = '([^']+)'/);
  assert.ok(cache, 'the cache name must be bumped so old caches are dropped');
  assert.ok(cache[1].startsWith('sridhar-rush-v'), 'cache name must be versioned: ' + cache[1]);
});

test('v142: setChip keeps icon and text as siblings so neither erases the other', () => {
  assert.match(GAME, /function setChip\(el, ico, text\)/, 'setChip helper must exist');
  const body = GAME.slice(GAME.indexOf('function setChip('), GAME.indexOf('function applyWeather('));
  assert.match(body, /el\.textContent = ''/, 'setChip clears the chip');
  assert.match(body, /setAttribute\('data-i', ico\)/, 'setChip writes the icon name');
  assert.match(body, /tx\.textContent = text/, 'setChip writes the label into its own span');
  assert.ok(!/el\.textContent = (?!'')/.test(body), 'setChip must never write text straight onto the chip (that erases the icon)');
});

test('v142: build versions stay consistent across every shipping surface', () => {
  // This is the check that should catch a half-done version bump. Previously the
  // suite pinned the literal ("v141"), so every release produced false failures -
  // and a genuinely inconsistent bump could still slip through.
  const g = read('public/js/game.js');
  const sw = read('public/sw.js');
  const html = read('public/index.html');
  const srv = read('server.js');

  const build = (g.match(/const BUILD = '(v\d+)'/) || [])[1];
  const cache = (sw.match(/const CACHE = 'sridhar-rush-(v\d+)'/) || [])[1];
  const srvBuild = (srv.match(/build: '(v\d+)'/) || [])[1];

  assert.ok(build, 'game.js must declare a build');
  assert.equal(cache, build, 'sw.js cache name must match the build (else stale icons/JS are served)');
  assert.equal(srvBuild, build, 'server.js /version must match the build (else the client reloads in a loop)');

  // every ?v= asset reference must be the same build. Note the two spellings:
  // BUILD/CACHE carry the "v" ("v142") while asset refs do not ("?v=142").
  const num = (x) => String(x).replace(/^v/, '');
  const want = num(build);
  const refs = [...html.matchAll(/\?v=(\d+)/g)].map((m) => m[1]);
  assert.ok(refs.length > 0, 'index.html must version its assets');
  for (const r of refs) assert.equal(r, want, `stale asset reference ?v=${r} (build is ${build})`);

  const swRefs = [...sw.matchAll(/\?v=(\d+)/g)].map((m) => m[1]);
  assert.ok(swRefs.length > 0, 'sw.js must version the files it precaches');
  for (const r of swRefs) assert.equal(r, want, `sw.js precaches a stale asset ?v=${r} (build is ${build})`);
});
