const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const publicJs = path.join(root, 'public', 'js');

fs.mkdirSync(publicJs, { recursive: true });

for (const file of ['game-core.js', 'progression.js', 'cosmetics.js']) {
  fs.copyFileSync(
    path.join(root, 'shared', file),
    path.join(publicJs, file)
  );
}

const config = [
  `window.SERVER_URL=${JSON.stringify(process.env.SERVER_URL || '')};`,
  `window.SB_U=${JSON.stringify(process.env.SUPABASE_URL || '')};`,
  `window.SB_A=${JSON.stringify(process.env.SUPABASE_ANON || '')};`,
  `window.C_WA=${JSON.stringify(process.env.COMMUNITY_WA || '')};`,
  `window.C_DC=${JSON.stringify(process.env.COMMUNITY_DC || '')};`
].join('');

fs.writeFileSync(path.join(publicJs, 'config.js'), config);

// v166: the offline shell needs to know every icon file and every car-model file
// by name. They are generated here so a new icon can never go missing from the
// saved copy of the game (test/offline-shell.test.js fails if this is stale).
function offlineFileList(dir) {
  const abs = path.join(root, 'public', dir);
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs).filter((f) => fs.statSync(path.join(abs, f)).isFile())
    .sort().map((f) => '/' + dir + '/' + f);
}
const offlineFiles = {
  icons: offlineFileList('img/ico').concat(offlineFileList('img/ico-mono')),
  heavy: offlineFileList('assets/cars/ghost')
};
fs.writeFileSync(path.join(root, 'public', 'sw-icons.js'),
  '// GENERATED by scripts/vercel-build.js - do not edit by hand.\n'
  + '// The files a saved-for-offline copy of the game needs beyond the shell:\n'
  + '// every drawn icon, and the shared car model.\n'
  + 'self.__SR_OFFLINE_FILES = ' + JSON.stringify(offlineFiles, null, 2) + ';\n');
console.log('[vercel-build] sw-icons.js: ' + offlineFiles.icons.length + ' icons, ' + offlineFiles.heavy.length + ' car-model files');
